"""Round-trip validation for the importer pipeline.

Two pieces:

- :func:`emit_script` — regenerate a runnable PSIM creation script from a
  :class:`~psim_mcp.importer.parser.ParsedSchematic`. Executing it with the
  PSIM-bundled Python rebuilds the ``.psimsch``; converting that file back
  with ``PsimConvertToPython`` and reconstructing again closes the loop:

      .psimsch → convert → parse → reconstruct = graph A
               → emit_script → run (PSIM) → .psimsch′
               → convert → parse → reconstruct = graph B
      compare_nets(A, B) → net-level precision/recall

- :func:`compare_nets` — compare the net partitions of two CircuitGraphs.
  Nets are compared as sets of pin-sets (net names are arbitrary), plus a
  pin-pair level precision/recall so partial overlaps are quantified.
"""

from __future__ import annotations

from itertools import combinations

from .graph import CircuitGraph
from .parser import ParsedComponent, ParsedSchematic


def _fmt(value: object) -> str:
    """Format a keyword value for the emitted script."""
    if isinstance(value, str):
        return repr(value)
    return repr(value)


def _emit_component(comp: ParsedComponent) -> list[str]:
    kwargs: list[str] = []
    meta = comp.metadata
    if meta.get("subtype") is not None:
        kwargs.append(f"SubType={_fmt(meta['subtype'])}")
    if meta.get("area") is not None:
        kwargs.append(f"AREA={meta['area']!r}")
    kwargs.append(f"DIRECTION={meta.get('direction') or 0}")
    kwargs.append("PAGE=0")
    kwargs.append(f"XFLIP={meta.get('xflip') or 0}")
    kwargs.append("_OPTIONS_=16")
    if meta.get("input_count") is not None:
        kwargs.append(f"_InputCount={meta['input_count']}")
    if meta.get("output_count") is not None:
        kwargs.append(f"_OutputCount={meta['output_count']}")
    ports_flat = [coord for pin in comp.pins for coord in pin]
    kwargs.append(f"PORTS={ports_flat!r}")

    # Multi-line parameters (e.g. CBLOCK CONTENT) go through PsimSetElmValue2
    # after creation — inline kwargs must stay single-line.
    inline_params = {}
    deferred_params = {}
    for key, value in comp.parameters.items():
        if isinstance(value, str) and ("\n" in value or "\r" in value):
            deferred_params[key] = value
        else:
            inline_params[key] = value
    for key, value in inline_params.items():
        kwargs.append(f"{key}={_fmt(value)}")

    lines = [
        "    nCreatedIndex = p1.PsimCreateNewElement(sch, "
        f"{comp.type!r}, {comp.name!r}, {', '.join(kwargs)})"
    ]
    for key, value in deferred_params.items():
        lines.append(
            f"    p1.PsimSetElmValue2(sch, {comp.type!r}, {comp.name!r}, {key!r}, {value!r})"
        )
    if comp.metadata.get("enabled") is False:
        lines.append("    p1.PsimEnableElm3(sch, nCreatedIndex, 0)")
    return lines


def emit_script(parsed: ParsedSchematic) -> str:
    """Regenerate a runnable PSIM creation script from parsed schematic data.

    Run with the PSIM-bundled Python:  ``python script.py <save_path>``
    (requires the ``PSIM_PATH`` environment variable).
    """
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""Auto-generated by psim_mcp.importer.roundtrip.emit_script."""',
        "import os",
        "import sys",
        "from psimapipy import PSIM",
        "",
        "",
        "def build(save_path):",
        '    p1 = PSIM(os.environ.get("PSIM_PATH", ""))',
        "    if not (p1 and p1.IsValid()):",
        '        raise RuntimeError("PSIM instance creation failed")',
        "    sch = p1.PsimFileNew()",
        "",
    ]

    for key, value in parsed.simulation.items():
        lines.append(f"    p1.PsimSetElmValue(sch, None, {key!r}, {value!r})")
    lines.append(
        '    p1.PsimCreateNewElement(sch, "SIMCONTROL", "", DIRECTION=0, '
        "AREA=[1200, 1100, 1240, 1140], PAGE=0, XFLIP=0, _OPTIONS_=0)"
    )
    lines.append("")

    for comp in parsed.components:
        lines.extend(_emit_component(comp))
    lines.append("")

    for label in parsed.labels:
        direction = label.metadata.get("direction") or 0
        lines.append(
            f'    p1.PsimCreateNewElement(sch, "LABEL", {label.name!r}, '
            f"DIRECTION={direction}, PORTS={list(label.point)!r}, "
            "PAGE=0, XFLIP=0, _OPTIONS_=16)"
        )
    lines.append("")

    for wire in parsed.wires:
        coords = []
        for i, (x, y) in enumerate(wire.points, start=1):
            coords.append(f'X{i}="{x}"')
            coords.append(f'Y{i}="{y}"')
        lines.append(f'    p1.PsimCreateNewElement(sch, "WIRE", "", PAGE=0, {", ".join(coords)})')
    lines.append("")

    lines.extend(
        [
            "    p1.PsimFileSave(sch, save_path)",
            "",
            "",
            'if __name__ == "__main__":',
            "    build(sys.argv[1])",
            "",
        ]
    )
    return "\n".join(lines)


def _partition(graph: CircuitGraph) -> set[frozenset[str]]:
    """Net partition as a set of pin-sets (net names are arbitrary)."""
    return {frozenset(net.pins) for net in graph.nets if len(net.pins) >= 2}


def _pin_pairs(partition: set[frozenset[str]]) -> set[frozenset[str]]:
    """All unordered same-net pin pairs — enables partial-overlap scoring."""
    pairs: set[frozenset[str]] = set()
    for net in partition:
        for a, b in combinations(sorted(net), 2):
            pairs.add(frozenset((a, b)))
    return pairs


def compare_nets(expected: CircuitGraph, actual: CircuitGraph) -> dict:
    """Compare net partitions of two graphs (expected vs reconstructed).

    Returns a report dict with exact net matching plus pin-pair level
    precision/recall (1.0 / 1.0 means electrically identical connectivity).
    """
    part_a = _partition(expected)
    part_b = _partition(actual)
    pairs_a = _pin_pairs(part_a)
    pairs_b = _pin_pairs(part_b)
    common = pairs_a & pairs_b

    precision = len(common) / len(pairs_b) if pairs_b else 1.0
    recall = len(common) / len(pairs_a) if pairs_a else 1.0

    return {
        "identical": part_a == part_b,
        "nets_expected": len(part_a),
        "nets_actual": len(part_b),
        "nets_matched": len(part_a & part_b),
        "nets_missing": [sorted(n) for n in sorted(part_a - part_b, key=sorted)],
        "nets_extra": [sorted(n) for n in sorted(part_b - part_a, key=sorted)],
        "pin_pair_precision": round(precision, 6),
        "pin_pair_recall": round(recall, 6),
    }
